###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Victor Admin",
    "email": "vmrf2000@hotmail.com",
    "password": "test1234",
    "role": "ADMIN"
}

###
# @name loginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "vmrf2000@hotmail.com",
    "password": "test1234"
}
###
@jwt_token = {{loginUser.response.body.access_token}}

###
GET http://localhost:3000/auth/profile
Authorization: Bearer {{jwt_token}}

###
# @name createEvent
POST http://localhost:3000/events
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "title": "Test event december",
    "description": "This is a another brand new test event",
    "date": "2025-12-04T10:00:00Z",
    "maxAttendees": 2,
    "price": 25,
    "address": {
        "street": "street test",
        "neighborhood": "neighborhood test",
        "city": "city test",
        "state": "state test",
        "country": "country test",
        "zipCode": "12345-678"
    }
}

###
@event_id = {{createEvent.response.body.id}}

###
GET http://localhost:3000/events
Authorization: Bearer {{jwt_token}}

###
GET http://localhost:3000/events/{{event_id}}
Authorization: Bearer {{jwt_token}}

###
GET http://localhost:3000/events/my-events
Authorization: Bearer {{jwt_token}}

###
PATCH  http://localhost:3000/events/{{event_id}}       
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "description": "This is a new test event",
  "price": 20.60,
  "address": {
    "street": "new street test",
    "neighborhood": "new neighborhood test",
    "city": "new city test",
    "state": "new state test",
    "country": "new country test",
    "zipCode": "98765-432"
  }
}

###
DELETE http://localhost:3000/events/{{event_id}}
Authorization: Bearer {{jwt_token}}

###
POST http://localhost:3000/orders
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "eventId": "{{event_id}}",
    "attendees": [
        {
            "name": "Fulano",
            "email": "email.teste.1@email.com"
        },
        {
            "name": "Beltrano",
            "email": "email.teste.3@email.com"
        }
    ]

}

###
GET http://localhost:3000/orders/my-orders
Authorization: Bearer {{jwt_token}}

###
PATCH http://localhost:3000/orders/event/feaab67a-84fa-4bfc-9245-9915e883739b/change-status
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "status": "CONFIRMED"
}

###
GET http://localhost:3000/orders/event/{{event_id}}
Authorization: Bearer {{jwt_token}}

###
DELETE http://localhost:3000/orders/{{event_id}}
Authorization: Bearer {{jwt_token}}

###
GET http://localhost:3000/events/{{event_id}}/attendess
Authorization: Bearer {{jwt_token}}


