###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Victor Admin",
    "email": "vmrf2000@hotmail.com",
    "password": "test1234",
    "role": "ADMIN"
}

###
# @name loginUser
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "vmrf2000@hotmail.com",
    "password": "test1234"
}
###
@jwt_token = {{loginUser.response.body.access_token}}

###
POST http://localhost:3000/events
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "title": "Test event",
    "description": "This is a test event",
    "date": "2025-10-01T10:00:00Z",
    "location": "Test Location",
    "maxAttendees": 20
}
